steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/${PROJECT_ID}/jq:${COMMIT_SHA}']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/${PROJECT_ID}/jq:${COMMIT_SHA}', 'gcr.io/${PROJECT_ID}/jq:${TAG_NAME}']
images:
  - 'gcr.io/${PROJECT_ID}/jq:${TAG_NAME}'
